# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dwi Siswanto
description: is writing...
repository: ""
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Dwi Siswanto
email: iam@dwisiswanto.id

navigation:
  - text: Home
    url: /
  - text: About
    url: https://dwisiswanto.id

social:
  - service: github
    username: dwisiswant0
    link: https://github.com/dwisiswant0
  - service: twitter
    username: dwisiswant0
    link: https://twitter.com/dwisiswant0

# Plugins
gems:
  - jekyll-seo-tag
